# -*- coding: utf-8 -*-
"""sba2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LHyKTW8SZ7xfaFSQAaZwubmpeEW92J4W

## Cara simpan: klik `file` -> `Download .py`. kemudian upload ke netacad di soal anda. 
**NOTE: SEBELUM ANDA SUBMIT SILAKAN DIJALANKAN TERLEBIH DAHULU APAKAH SCRIPT/KODE ANDA BEBAS DARI ERROR ATAU TIDAK**.
"""

'''
namafile: sba.py
Lembar kerja/script Latihan SBA
'''
# >>>>>>LEMBAR KERJA>>>>>>>>>
# lembar ini hanya berisi pendefinisian fungsi dan class saja
 
#email netacad
email = 'iqbal.hanif.ipb@gmail.com'
 
# >>>>>>Soal 1
def fungsiIO():
  pass
  # Mulai kode anda dari sini
  x = list(map(int, input().split()))
  y = sorted(x)
  for i in range(0,len(y)):
    z = '*'*y[i]
    print(z)
  
   
# >>>>>>Akhir Soal 1 
 
# >>>>>>Soal 2
def caseShopia(txt):
  pass
  # Mulai kode anda dari sini
  x = txt
  y = [char for char in x]
  z = []
  for i in range(0, len(y)):
    if y[i].isalpha() == True:
      if y[i].islower() == True:
        z.append(y[i].upper()) 
      else:
        z.append(y[i].lower())
    else:
      continue 

  a = ''.join(z)
  return(a)
  

# >>>>>>Akhir Soal 2 
 
# Jangan diubah biarkan seperti ini
dcur2idr = {'USD': 14425, 'EUR': 16225, 'AUD': 9925, 'CAD': 10500, 
             'GBP': 17800, 'CHF': 15200, 'SGD': 10375, 'HKD': 1775, 
             'JPY': 132500, 'MYR': 3250, 'SAR': 3500, 'WON': 10750, 
             'IDR': 1}
 
# >>>>>> Soal 3 
pass
# Mulai kode anda dari sini
def usd2eur(usd):
  x = float(usd * (dcur2idr['USD']/dcur2idr['EUR']))
  return x
 
 
# >>>>>>Akhir Soal 3 
 
# >>>>>>Soal 4 
class MoneyChanger:  
  def __init__(self, dcurrency, base, percent=2):
    pass
    # Mulai kode anda dari sini
    self.dcurrency = dcurrency
    self.base = base
    self.percent = int(percent)

  def selling_price(self, nominal, curr):
    pass
    # Mulai kode anda dari sini
    nominal = float(nominal)
    a = nominal*(dcur2idr[curr]/dcur2idr[self.base]) + self.percent/100 * (nominal*(dcur2idr[curr]/dcur2idr[self.base]))
    return a

  def buying_price(self, nominal, curr):
    pass
    # Mulai kode anda dari sini
    nominal = float(nominal)
    a = nominal*(dcur2idr[curr]/dcur2idr[self.base]) - self.percent/100 * (nominal*(dcur2idr[curr]/dcur2idr[self.base]))
    return a

  def change_base(self,new_base):
    pass
    # Mulai kode anda dari sini
    self.base = new_base

 
# >>>>>>Akhir Soal 4 
 
# >>>>>>AKHIR LEMBAR KERJA>>>>>>>>>
 
 
 
# KODE DI BAWAH INI UNTUK TESTING
# ANDA BOLEH MEMBUANG SEMUA KODE DI SAAT SUBMISI KE NETACAD
 
def main():
  pass
  # >>>>>TEST DI SINI>>>>>>
  # gunakan BLOCK MAIN ini untuk mengetes
  # untuk pengetesan kode hanya boleh di bagian sini
  # silakan test sesuka hati di sini
 
  #############################################
  # uncomment script di bawah ini untuk testing
  #############################################
  
  # print('test soal 1')
  # fungsiIO() # contoh input: 7 4 5 2 1 3
 
  # print('test soal 2')
  # print(caseShopia('thXGth876%^$LMn.'))
 
  # print('test soal 3')
  # print(usd2eur(100))  # mengubah 100 USD ke EUR
 
  # print('test soal 4')
  # mc = MoneyChanger(dcur2idr,base='EUR') # object mc dengan base EUR
  # print('base', mc.base)
  # print(mc.selling_price(100,'USD')) # nilai jual 100 USD ke EUR (Base)
  # print(mc.buying_price(100,'USD')) # nilai beli 100 USD ke EUR (Base)
  
  # mc.change_base('IDR') # Ganti Base object mc ke IDR
  # print('base', mc.base)
  # print(mc.selling_price(100,'USD')) # nilai jual 100 USD ke IDR (Base)
  # print(mc.buying_price(100,'USD'))  # nilai beli 100 USD ke IDR (Base)
 
  # >>>>>AKHIR TEST DI SINI>>>>>>
 
if __name__ == '__main__':
  main()